openapi: 3.0.3
info:
  title: MR Banners API
  version: "1.0.0"
servers:
  - url: https://example.local
paths:
  /banners:
    get:
      summary: Get banners (demo)
      description: >
        Демонстрационная операция для Microcks.
        Через query-параметр `mode` можно переключать сценарий: ok | error.
      parameters:
        - in: query
          name: mode
          required: false
          schema:
            type: string
            enum: [ok, error]
          description: Если `error` — вернём 500.
      responses:
        "200":
          description: OK
          headers:
            X-Trace-Id:
              schema:
                type: string
              description: Трассировочный ID, может приходить из запроса
          content:
            application/json:
              examples:
                ok:
                  summary: Successful banners list
                  value:
                    data:
                      - id: "bnr-101"
                        title: "Spring Sale"
                        imageUrl: "https://cdn.example/banners/spring.jpg"
                        locale: "ru_RU"
                      - id: "bnr-102"
                        title: "Cashback 5%"
                        imageUrl: "https://cdn.example/banners/cashback.jpg"
                        locale: "ru_RU"
                    meta:
                      requestId: "{{request.headers.X-Request-Id}}"
                      ts: "{{ now() }}"
        "500":
          description: Simulated error
          content:
            application/json:
              examples:
                server-error:
                  summary: Forced 500 error
                  value:
                    error: "Internal Server Error"
                    code: "SIMULATED_500"
                    details: "Forced by Microcks"
                    requestId: "{{request.headers.X-Request-Id}}"
