openapi: 3.0.3
info:
  title: MR Demo API
  version: "1.0.0"
servers:
  - url: https://example.local
paths:
  /banners:
    get:
      summary: Get banners (demo)
      description: Demo endpoint for Microcks mocking
      parameters:
        - in: query
          name: mode
          required: false
          schema:
            type: string
            enum: [ok, error]
          description: Optional switch for dispatcher rules
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        imageUrl:
                          type: string
                  total:
                    type: integer
              examples:
                ok:
                  value:
                    items:
                      - id: "bnr-1001"
                        title: "Welcome bonus"
                        imageUrl: "https://cdn.example/banners/welcome.png"
                      - id: "bnr-2002"
                        title: "Cashback weekend"
                        imageUrl: "https://cdn.example/banners/cashback.png"
                    total: 2
        "500":
          description: Simulated server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  code:
                    type: string
                  requestId:
                    type: string
              examples:
                server-error:
                  value:
                    error: "Internal Server Error"
                    code: "SIMULATED_500"
                    requestId: "{{request.headers.X-Request-Id}}"
